Debug watch performer
MasteraVodoProvodchiki/frox pull request #20
Opened 2020-04-15 20:45 UTC by Guilder1333

Additional methods making editor able to access performer data for each node output pin.

2020-04-16 16:04 UTC, Dmitry666 requested changes

2020-04-16 16:04 UTC, Dmitry666 commented on Frox/Guid.h
> +	friend bool operator == (const Guid& left, const Guid& right);
На сколько я помню эти методы были специально в .h, чтобы класс можно было использовать за пределами проекта без необъодимости экспорта

2020-04-16 16:04 UTC, Dmitry666 commented on Frox/InRangeComputeNode.cpp
> -	cv::Scalar minTresh(low);
Предлогаю не комитеть измнения кокончания строк

2020-04-16 16:04 UTC, Dmitry666 commented on FroxKinect2/Kinect2Inspector.cpp
> +#include "Kinect2Inspector.h"
А здесь весь файл с изменениями. Предлогаю оставить только реальные изменения,а не окончания строк

2020-04-16 16:17 UTC, Guilder1333 commented on Frox/Guid.h
> +	friend bool operator == (const Guid& left, const Guid& right);
Он же приватный

2020-04-16 18:02 UTC, Guilder1333 commented
Что-то странная как-то печально, VS это не видит, clion тоже, видит только гит. Ща еще раз попробую убрать.

2020-04-16 18:14 UTC, Dmitry666 requested changes

2020-04-16 18:14 UTC, Dmitry666 commented on Frox/BasicFlowPerformer.cpp
> +DebugFlowDataPtr BasicFlowPerformer::GetLatestPerformedDataForDebug() const {
У нас скобки с новой строки

2020-04-16 18:14 UTC, Dmitry666 commented on Frox/BasicFlowPerformerImpl.cpp
> +			case EPinValueType::Value: {
Тут всё ещё изменения, которых нет

2020-04-16 18:18 UTC, Guilder1333 commented
Все, удалось убрать лишние ченжи.

2020-04-17 04:31 UTC, SergChernykh approved these changes

2020-04-17 10:03 UTC, Dmitry666 requested changes

2020-04-17 10:03 UTC, Dmitry666 commented on Frox/Guid.cpp
> +		return false;
Codestyle. У нас всегда есть {}

2020-04-17 10:03 UTC, Dmitry666 commented on Frox/Guid.cpp
> +			if (i >= 32)
Codestyle. У нас всегда есть {}

2020-04-17 10:03 UTC, Dmitry666 commented on Frox/Guid.cpp
> +		return false;
Codestyle. У нас всегда есть {}

2020-04-17 19:48 UTC, merged